name: Deployment

on:
  push:
    branches: [ test ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'https://gitnoter.com'
    steps:
      - name: 'Install latest helm'
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: 'Install latest helm'
        uses: azure/setup-helm@v1

      - name: Deploy to production
        env:
          HELM_REPO: 'https://vivekweb2013.github.io/gitnoter-charts/'
        run: |
          kubectl version
